---
meta:
  name: blacksmith
  target: blacksmith
  url: (( vault "secret/pipelines/concourse:url" ))
  
  git:
    email: ci@starkandwayne.com
    name: CI Bot

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner: cloudfoundry-community
    repo: blacksmith
    access_token: (( vault "secret/pipelines/blacksmith/github:token" ))
    private_key: (( vault "secret/pipelines/blacksmith/github:private" ))

  slack:
    webhook: (( vault "secret/pipelines/blacksmith/slack:webhook" ))
    channel: "#botspam"
